apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-custom-page
data:
  custom-page.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LW Nginx Page</title>
    </head>
    <body>
    <h1>Hello from LW Nginx Page!</h1>
    <p>This is a LW custom page served by Nginx using Kubernetes ConfigMap.</p>
    </body>
    </html>
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;
        location / {
          root /usr/share/nginx/html;
          index custom-page.html;
        }
      }
    }