apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-custom
  labels:
    app: nginx-custom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-custom
  template:
    metadata:
      labels:
        app: nginx-custom
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: custom-page
          mountPath: /usr/share/nginx/html/custom-page.html
          subPath: custom-page.html
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: custom-page
        configMap:
          name: nginx-custom-page
          items:
          - key: custom-page.html
            path: custom-page.html
      - name: nginx-config
        configMap:
          name: nginx-custom-page
          items:
          - key: nginx.conf
            path: nginx.conf